spring:
  application:
    name: bookgateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"  # List all origins or use "*" for all
            allowedMethods: 
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - Content-Type
              - Authorization
              - Accept
              - Origin
              - X-Requested-With
            allowCredentials: true
            maxAge: 3600
      routes:        
        - id: book
          uri: lb://BOOKSTORE
          predicates:
            - Path=/store/**
          filters:
            - RewritePath=/store/(?<segment>.*), /$\{segment}
        - id: bookauth-service
          uri: lb://BOOKAUTH
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}  
            - RemoveDuplicateCorsHeadersFilter
        - id: spms-service
          uri: lb://SPMS
          predicates:
            - Path=/spms/**
          filters:
            - RewritePath=/spms/(?<segment>.*), /$\{segment}
    discovery:
      locator:
        enabled: true

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}


